/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/Home/Cards.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Introduction: typeof import('./src/components/Home/Introduction.vue')['default']
    MaterialContent: typeof import('./src/components/Home/MaterialContent.vue')['default']
    Phrase1: typeof import('./src/components/Home/Phrase1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
